### ISSUE TITLE
Building windows on mac

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/r-shiny-electron#25]
For the record:

Install `wine` and `mono`
then
`electron-forge make --platform=win32`

---
Using homebrew
`brew install wine`

Install mono using the installer https://www.mono-project.com/download/stable/

**Comment by rpodcast** [comment]
I'm trying to follow a similar workflow to build a Shiny app as a windows standalone executable, and since I don't have access to a Windows machine myself, I am using my Mac to compile it.  I launched `electron-forge make --platform=win32` and it still has not finished the "packaging application" step (it has been 5 hours as I type this).  Is it supposed to take that long?

**Comment by eliasdev** [comment]
I'm running electron-forge make  --platform=win32

Getting the following error:

✔ Compiling Application
✔ Preparing native dependencies
⠋ Packaging Application
An unhandled rejection has occurred inside Forge:
spawn Unknown system error -86
Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at module.exports (/usr/local/lib/node_modules/electron-forge/node_modules/rcedit/lib/rcedit.js:47:15)
    at /usr/local/lib/node_modules/electron-forge/node_modules/pify/index.js:49:6
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/electron-forge/node_modules/pify/index.js:11:9
    at ret (/usr/local/lib/node_modules/electron-forge/node_modules/pify/index.js:72:32)
    at /usr/local/lib/node_modules/electron-forge/node_modules/electron-packager/win32.js:95:39

os X Catalina 10.15.5

Any idea why?
